export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const ACCOUNT_PROFILE_REQUEST = 'ACCOUNT_PROFILE_REQUEST';
export const ACCOUNT_PROFILE_RECEIVED = 'ACCOUNT_PROFILE_RECEIVED';
export const ACCOUNT_PROFILE_ERROR = 'ACCOUNT_PROFILE_ERROR';
