export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const ACCOUNT_PROFILE_REQUEST = 'ACCOUNT_PROFILE_REQUEST';
export const ACCOUNT_PROFILE_RECEIVED = 'ACCOUNT_PROFILE_RECEIVED';
export const ACCOUNT_PROFILE_ERROR = 'ACCOUNT_PROFILE_ERROR';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const PEAK_REQUEST = 'PEAK_REQUEST';
export const PEAK_RECEIVED = 'PEAK_RECEIVED';
export const PEAK_ERROR = 'PEAK_ERROR';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';

export const NEW_POST_REQUEST = 'NEW_POST_REQUEST';
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export const NEW_POST_ERROR = 'NEW_POST_ERROR';
export const NEW_POST_RESET = 'NEW_POST_RESET';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_RESET = 'DELETE_POST_RESET';
