export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const ACCOUNT_PROFILE_REQUEST = 'REQUEST_ACCOUNT_PROFILE';
export const ACCOUNT_PROFILE_RECEIVE = 'RECEIVE_ACCOUNT_PROFILE';
export const ACCOUNT_PROFILE_ERROR = 'ERROR_ACCOUNT_PROFILE';
