export const AUTH_FORM_UPDATE = "AUTH_FORM_UPDATE";
export const GOAL_FORM_UPDATE = "GOAL_FORM_UPDATE";
export const REDIRECT_TO_PROFILE = "REDIRECT_TO_PROFILE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const ACCOUNT_PROFILE_REQUEST = "ACCOUNT_PROFILE_REQUEST";
export const ACCOUNT_PROFILE_RECEIVED = "ACCOUNT_PROFILE_RECEIVED";
export const ACCOUNT_PROFILE_ERROR = "ACCOUNT_PROFILE_ERROR";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const PEAK_REQUEST = "PEAK_REQUEST";
export const PEAK_RECEIVED = "PEAK_RECEIVED";
export const PEAK_ERROR = "PEAK_ERROR";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";

export const CREATE_USER_GOAL_REQUEST = "CREATE_USER_GOAL_REQUEST";
export const CREATE_USER_GOAL_SUCCESS = "CREATE_USER_GOAL_SUCCESS";
export const CREATE_USER_GOAL_ERROR = "CREATE_USER_GOAL_ERROR";

export const UPDATE_USER_GOAL_REQUEST = "UPDATE_USER_GOAL_REQUEST";
export const UPDATE_USER_GOAL_SUCCESS = "UPDATE_USER_GOAL_SUCCESS";
export const UPDATE_USER_GOAL_ERROR = "UPDATE_USER_GOAL_ERROR";

export const DELETE_USER_GOAL_REQUEST = "DELETE_USER_GOAL_REQUEST";
export const DELETE_USER_GOAL_SUCCESS = "DELETE_USER_GOAL_SUCCESS";
export const DELETE_USER_GOAL_ERROR = "DELETE_USER_GOAL_ERROR";
